### PR TITLE
Conform Room Reservation Feature to CSXL's Material UI Conventions

### PR DESCRIPTION
**Pull request by ajaygandecha**
This pull request makes UI modifications to the amazing new Room Reservation Feature to conform to the CSXL site's current Material UI usage and standards.

## Major Changes

Screenshot 2024-03-08 at 11 15 52 PM

- Embedded the main page into a card component, using the outlined style, with a title.
- Right-aligned the date picker to make room for the title, and update the date picker to use the outlined style.
- Modified the save / reserve button to use the outlined style.
- Rounded the square color key items in the legend.
- Removed the "Total Hours Remaining" label (if we want to add this back, no problem! I think we would need to find a good placement for it though)

### CODE REVIEW

**Comment by yuvrajjain2003** [comment]
Added @aarjavjain2002 for the review, since he was the one who primarily worked on the frontend UI for the table!

**Comment by ajaygandecha** [comment]
Great points @yuvrajjain2003! I actually forgot that was what that label represented - thought it was how long until the XL closed lol - I added it as a mat subtitle, think it fits there!

Screenshot 2024-03-09 at 12 02 16 AM

I also added some extra CSS to make sure that the date picker automatically realigns below the title on mobile.

Also, for the reserve button not scrolling with the table, I believe this also was the case in the design currently pushed in the XL site! I did not change anything from there. Will try to refactor the overflow scrolling a bit to add this functionality.

**Comment by ajaygandecha** [comment]
@yuvrajjain2003 yup, got the Reserve button sticking to the left side implemented! Pushed in latest commit.

**Review by yuvrajjain2003 — APPROVED** [review]
LGTM! These changes look great! The UI is looking much more consistent with the rest of the site!

**Review by aarjavjain2002 — APPROVED** [review]
LGTM! Love the new UI. I like how the table is within a container that enables scrolling in the widget itself. Also the hours under the heading looks really good. You really embellished our new feature with this makeover, Ajay!

**Comment by KrisJordan** [comment]
Great work tidying/abstracting this component out and aligning its design with the rest of the material look @ajaygandecha  Thanks for the reviews @yuvrajjain2003 and @aarjavjain2002

**Review by KrisJordan — APPROVED** [review]
LGTM!

**Pull request merged**
