### PR TITLE
Create Models for Course Feature

### PR DESCRIPTION
**Pull request by ajaygandecha**
This major pull request makes progress on adding all of the necessary models for the courses feature to function. This includes including courses, terms (semesters), course sections, and the necessary details models to store relationships.

### CODE REVIEW

**Comment by ajaygandecha** [comment]
@KrisJordan made some initial progress on the models here. The main question I had here is how we want to handle models for the join table (`user_section`). Is this something we want a model for that matches the database, or do we want a custom model here such as a SectionRosterItem or something like that?

I imagine the use case would be that we have an API that gets the roster of a course.

There are a few approaches:
- Add a new subclass of `SectionDetails` that contains information on the members of the course, and this is populated by the service function.
- Add model to represent join table data, populated with service functions.

**Comment by KrisJordan** [comment]
This is where some differentiation between instructor/staff and students may come into the mix. We likely want an easy way to have limited instructor information (first/last/pronouns/email) modeled for front-end purposes. It's a little less clear how much of TA information we want in the front-end for privacy purposes: likely depends on the feature (students in the class can see, but not publicly listed). Finally, student enrollments needs to be very private by default and access control here will be important.

For now, I'd suggest focusing on the design of modeling `SectionStaff` and assuming it's generally served up as a member of `SectionDetails`. This would have a field of type of staff (instructor/uta/gta).

I think until we have a feature that needs to involve students self-associating with a class, let's leave that association unrepresentable as a model for the short term. That said, going down the road of `SectionDetailsWithRoster`, or something, where the students field is actually a list of User, _may_ make more sense than adding a special model for `Student`.

**Comment by ajaygandecha** [comment]
@KrisJordan do you think it is better to keep the staff field of `SectionDetails` default to `[]` and then have the service fill the list? Without this, we would need to re-add a relationship field I think

**Comment by KrisJordan** [comment]
That seems fine, yeah.

**Comment by ajaygandecha** [comment]
Alright @KrisJordan, ready for initial review! 😄

**Review by KrisJordan — APPROVED** [review]
This lgtm!

**Pull request merged**
